### ISSUE TITLE
Windows: files listed in binding.gyp are missing in VidyoClient-WindowsSDK (4.1.18.8)

### ISSUE THREAD

**Issue by alhambra1** [Vidyo/VidyoConnector-electron#1]
These lines in file, "binding.gyp" seem to generate errors during build because the files are missing in the current VidyoClient-WindowsSDK (version 4.1.18.8).

Are these files important?

            "-l<!(echo %VIDYO_CLIENT_LIB_DIR%)\\celt",
            "-l<!(echo %VIDYO_CLIENT_LIB_DIR%)\\silk_common",
            "-l<!(echo %VIDYO_CLIENT_LIB_DIR%)\\silk_fixed",
            "-l<!(echo %VIDYO_CLIENT_LIB_DIR%)\\silk_float"

**Comment by pfuternik** [comment]
Thank you for pointing this out. We have removed those lines from binding.gyp, which aren't necessary.

**Comment by chenmengvidyo** [comment]
Removed from binding.gyp linking of library files that are no-longer in Vidyo Client distribution.
