### ISSUE TITLE
Nothing displays in renderer

### ISSUE THREAD

**Issue by mrobrian** [Vidyo/VidyoConnector-electron#2]
After spending most of the day figuring out which specific versions of python and VS tools I need, I was finally able to get this add-on built and put in the correct place so my Electron-based app can load it. When running my application outside of Electron, in Chrome, Vidyo works great. When running inside Electron, the remote side can see my video, but the "renderer" view is blank. There are no errors or warnings in the console, nor any alerts that pop up.

When I inspect the renderer element while running Chrome I see that it has a several elements within it, including a video element. When I inspect the same element in Electron, while running the exact same code, the renderer element is empty.

I'm assuming I must be missing something, but I followed all of the steps in the readme... The add-on was built using the same version of Electron as the app, the add-on loads in Electron just fine, and I even tried running the Connector installer program just in case that was needed. I've tried this on two different devices, a desktop computer and a tablet, and both have the same issue.

**Comment by pfuternik** [comment]
Are you working on Windows 10? This sounds like an issue that was introduced with Windows 10 update 1709 which prevents video from rendering properly. The workaround is to upgrade to the latest Electron (currently v1.8.3) and to disable hardware acceleration, which can be done as follows in main.js:
app.disableHardwareAcceleration();

**Comment by mrobrian** [comment]
I am working on Windows 10. Unfortunately, we are unable to update our version of Electron at this time. The version we're using is locked down through our current release cycle, and then we can research any breaking changes between our current version and the latest to see what it would take to upgrade. I'd also be hesitant to turn off hardware acceleration without thoroughly testing how it would affect the rest of the application.

Since it seems there is a known fix for this problem, feel free to close out this ticket. We'll likely be going with a different solution for now.

**Comment by pfuternik** [comment]
Ok makes sense. What version of Electron are you using?
